/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Uber;
import model.UberHistory;

/**
 *
 * @author kashr
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    UberHistory history;
    
    public CreateJPanel(UberHistory history) {
        initComponents();
        this.history=history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        lblseatNo = new javax.swing.JLabel();
        txtseatNo = new javax.swing.JTextField();
        lblManufacturer = new javax.swing.JLabel();
        lblManufactureYear = new javax.swing.JLabel();
        lblSerialNo = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblModelNo = new javax.swing.JLabel();
        lblMaintanenceCert = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        chkAvailability = new javax.swing.JCheckBox();
        txtManufacturer = new javax.swing.JTextField();
        txtSerialNo = new javax.swing.JTextField();
        txtModelNo = new javax.swing.JTextField();
        txtManufactureYear = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtMaintanenceCert = new javax.swing.JTextField();
        lblvaliseat = new javax.swing.JLabel();
        lblyearvali = new javax.swing.JLabel();
        lblcompany = new javax.swing.JLabel();
        txtcompany = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 255, 153));

        lblTitle.setBackground(new java.awt.Color(255, 0, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnsave.setBackground(new java.awt.Color(153, 0, 153));
        btnsave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        lblseatNo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblseatNo.setText("No of Seats");

        txtseatNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseatNoActionPerformed(evt);
            }
        });
        txtseatNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtseatNoKeyPressed(evt);
            }
        });

        lblManufacturer.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblManufacturer.setText("Manufacturer");

        lblManufactureYear.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblManufactureYear.setText("Manufacture Year");

        lblSerialNo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblSerialNo.setText("Serial No");

        lblCity.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblCity.setText("City");

        lblModelNo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblModelNo.setText("Model No");

        lblMaintanenceCert.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblMaintanenceCert.setText("Maintanence Cert");

        lblAvailability.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblAvailability.setText("Availability");

        chkAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAvailabilityActionPerformed(evt);
            }
        });

        txtManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturerActionPerformed(evt);
            }
        });

        txtSerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNoActionPerformed(evt);
            }
        });

        txtModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNoActionPerformed(evt);
            }
        });

        txtManufactureYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufactureYearActionPerformed(evt);
            }
        });
        txtManufactureYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtManufactureYearKeyPressed(evt);
            }
        });

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        txtMaintanenceCert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaintanenceCertActionPerformed(evt);
            }
        });

        lblcompany.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblcompany.setText("company");

        txtcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompanyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblseatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManufacturer)
                            .addComponent(lblManufactureYear)
                            .addComponent(lblSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaintanenceCert)
                            .addComponent(lblcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaintanenceCert, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkAvailability)
                            .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtseatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblyearvali)
                                    .addComponent(lblvaliseat)))
                            .addComponent(txtcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(btnsave)))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtseatNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblvaliseat))
                    .addComponent(lblseatNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblyearvali))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(lblModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaintanenceCert, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaintanenceCert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAvailability)
                    .addComponent(lblAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnsave)
                .addContainerGap(323, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        int seatNo= Integer.parseInt(txtseatNo.getText());
        int manufactureYear=Integer.parseInt(txtManufactureYear.getText());
        String modelNo=txtModelNo.getText();
        String city=txtCity.getText();
        String serialNo=txtSerialNo.getText();
        int maintananceCert=Integer.parseInt(txtMaintanenceCert.getText());
        String manufacturer=txtManufacturer.getText();
        boolean availability=chkAvailability.isSelected();
        String company=txtcompany.getText();
     
        
        Uber u=history.addNewUbers();
        
        u.setSeatNo(seatNo);
        u.setMaintananceCert(maintananceCert);
        u.setModelNo(modelNo);
        u.setCity(city);
        u.setSerialNo(serialNo);
        u.setManufactureYear(manufactureYear);
        u.setManufacturer(manufacturer);
        u.setAvailability(availability);
        u.setcompany(company);
        
        
        JOptionPane.showMessageDialog(this,"New Car added.");
        
        txtseatNo.setText("");
        txtManufactureYear.setText("");
        txtModelNo.setText("");
        txtCity.setText("");
        txtSerialNo.setText("");
        txtMaintanenceCert.setText(""); 
        txtManufacturer.setText("");
        chkAvailability.isSelected();
        txtcompany.setText("");
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtseatNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseatNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtseatNoActionPerformed

    private void chkAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAvailabilityActionPerformed

    private void txtManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturerActionPerformed

    private void txtSerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNoActionPerformed

    private void txtModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNoActionPerformed

    private void txtManufactureYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufactureYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufactureYearActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtMaintanenceCertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaintanenceCertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaintanenceCertActionPerformed

    private void txtseatNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtseatNoKeyPressed
        // TODO add your handling code here:
                
        char modelNumKeyPressed = evt.getKeyChar();
        if(Character.isLetter(modelNumKeyPressed)){
            txtseatNo.setEditable(false);
            lblvaliseat.setText("Please enter number Only!");
        }
        else
        {
            txtseatNo.setEditable(true);
            lblvaliseat.setText("");
        }
    }//GEN-LAST:event_txtseatNoKeyPressed

    private void txtManufactureYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManufactureYearKeyPressed
        // TODO add your handling code here:
                char modelNumKeyPressed = evt.getKeyChar();
        if(Character.isLetter(modelNumKeyPressed)){
            txtManufactureYear.setEditable(false);
            lblyearvali.setText("Please enter number Only!");
        }
        else
        {
            txtManufactureYear.setEditable(true);
            lblyearvali.setText("");
        }
    }//GEN-LAST:event_txtManufactureYearKeyPressed

    private void txtcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcompanyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JCheckBox chkAvailability;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblMaintanenceCert;
    private javax.swing.JLabel lblManufactureYear;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblModelNo;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblcompany;
    private javax.swing.JLabel lblseatNo;
    private javax.swing.JLabel lblvaliseat;
    private javax.swing.JLabel lblyearvali;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtMaintanenceCert;
    private javax.swing.JTextField txtManufactureYear;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtSerialNo;
    private javax.swing.JTextField txtcompany;
    private javax.swing.JTextField txtseatNo;
    // End of variables declaration//GEN-END:variables
}
