/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.time.LocalDate;
import model.Uber;
import model.UberHistory;

/**
 *
 * @author kashr
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    UberHistory history;
    
    
    public MainJFrame() {
        initComponents();
        
        history = new UberHistory();
        setData();//sets the initialized data into the array
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setBackground(new java.awt.Color(102, 255, 204));

        controlPanel.setBackground(new java.awt.Color(102, 255, 204));

        btnCreate.setBackground(new java.awt.Color(0, 51, 255));
        btnCreate.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Add New Car");
        btnCreate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(51, 51, 255));
        btnView.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("Services");
        btnView.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(btnCreate)
                .addGap(35, 35, 35)
                .addComponent(btnView)
                .addContainerGap(696, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Logo.jpg"))); // NOI18N

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 973, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // definig button action to connect create Panel
        CreateJPanel createPanel=new CreateJPanel(history);
        splitPane.setRightComponent(createPanel);
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewPanel=new ViewJPanel(history);
        splitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnViewActionPerformed
    public void setData() {

        Uber u = history.addNewUbers();

        u.setModelNo("A1");
        u.setSerialNo("1ATC");
        u.setManufacturer("Ford");
        u.setManufactureYear(1996);
        u.setSeatNo(7);
        u.setcompany("Pink");
        u.setAvailability(true);
        /*u.setLastUpdated("06-09-2015");*/
        u.setCity("Chennai");
        u.setMaintananceCert(1);

        Uber u1 = history.addNewUbers();

        u1.setModelNo("Xyz");
        u1.setSerialNo("5Ft");
        u1.setManufacturer("BMW");
        u1.setManufactureYear(2009);
        u1.setSeatNo(5);
        u1.setcompany("Lyft");
        u1.setAvailability(true);
        //u1.setLastUpdated("12-11-2020");
        u1.setCity("Boston ");
       u1.setMaintananceCert(20);

        Uber u2 = history.addNewUbers();

        u2.setModelNo("abc");
        u2.setSerialNo("H78");
        u2.setManufacturer("BMW");
        u2.setManufactureYear(2021);
        u2.setSeatNo(4);
        u2.setcompany("Pink");
        u2.setAvailability(true);
        //u2.setLastUpdated("10-06-2021");*/
        u2.setCity("NYC");
        u2.setMaintananceCert(60);

        Uber u3 = history.addNewUbers();

        u3.setModelNo("abc");
        u3.setSerialNo("18F");
        u3.setManufacturer("Ford");
        u3.setManufactureYear(2019);
        u3.setSeatNo(7);
        u3.setcompany("Pink");
        u3.setAvailability(false);
        //u3.setLastUpdated("12-11-2013");
        u3.setCity("Chennai");
        u3.setMaintananceCert(87);

        Uber u4 = history.addNewUbers();

        u4.setModelNo("B2");
        u4.setSerialNo("POK09");
        u4.setManufacturer("Subaru");
        u4.setManufactureYear(1998);
        u4.setSeatNo(5);
        u4.setcompany("Lyft");
        u4.setAvailability(true);
        //u4.setLastUpdated("09-01-2019");*/
        u4.setCity("Boston");
        u4.setMaintananceCert(74);

        Uber u5 = history.addNewUbers();

        u5.setModelNo("B9");
        u5.setSerialNo("JKL33");
        u5.setManufacturer("Subaru");
        u5.setManufactureYear(2009);
        u5.setSeatNo(5);
        u5.setcompany("Pink");
        u5.setAvailability(true);
        //u5.setLastUpdated("06-09-2017");
        u5.setCity("New York");
        u5.setMaintananceCert(58);
        
        Uber u6 = history.addNewUbers();

        u6.setModelNo("Cute");
        u6.setSerialNo("GUI6");
        u6.setManufacturer("BMW");
        u6.setManufactureYear(2021);
        u6.setSeatNo(2);
        u6.setcompany("Lyft");
        u6.setAvailability(true);
        //u6.setLastUpdated("06-09-2017");*/
        u6.setCity("NYC");
        u6.setMaintananceCert(49);
      
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables


    }

