/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Uber;
import model.UberHistory;

/**
 *
 * @author kashr
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    UberHistory history;
    public ViewJPanel(UberHistory history) {
        initComponents();
        
        this.history=history;      
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUber = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblSerialNo = new javax.swing.JLabel();
        txtMaintanenceCert = new javax.swing.JTextField();
        lblseatNo = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtseatNo = new javax.swing.JTextField();
        lblModelNo = new javax.swing.JLabel();
        lblMaintanenceCert = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        chkAvailability = new javax.swing.JCheckBox();
        txtManufacturer = new javax.swing.JTextField();
        txtSerialNo = new javax.swing.JTextField();
        txtModelNo = new javax.swing.JTextField();
        lblManufacturer = new javax.swing.JLabel();
        txtManufactureYear = new javax.swing.JTextField();
        lblManufactureYear = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtsearchmanufacturer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblsortbymanufacture = new javax.swing.JLabel();
        lblsortbyyear = new javax.swing.JLabel();
        txtsearchyear = new javax.swing.JTextField();
        lblsortbycity = new javax.swing.JLabel();
        txtsearchcity = new javax.swing.JTextField();
        txtsearchmodelno = new javax.swing.JTextField();
        lblsortbymodelno = new javax.swing.JLabel();
        lblsearchavailable = new javax.swing.JLabel();
        txtAvail = new javax.swing.JTextField();
        btnfirstavail = new javax.swing.JButton();
        lblcompany = new javax.swing.JLabel();
        txtcompany = new javax.swing.JTextField();
        lblsortbycompany = new javax.swing.JLabel();
        txtsearchcompany = new javax.swing.JTextField();
        txtseat1 = new javax.swing.JTextField();
        txtseat2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnexpmain = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));

        lblTitle.setBackground(new java.awt.Color(255, 0, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tblUber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Manufacturer", "Seat No", "Manufacture Year", "Serial No", "Model No", "City", "Maintanence Cert", "Availability", "Company"
            }
        ));
        tblUber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUber);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblSerialNo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblSerialNo.setText("Serial No");

        txtMaintanenceCert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaintanenceCertActionPerformed(evt);
            }
        });

        lblseatNo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblseatNo.setText("No of Seats");

        lblCity.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblCity.setText("City");

        txtseatNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseatNoActionPerformed(evt);
            }
        });

        lblModelNo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblModelNo.setText("Model No");

        lblMaintanenceCert.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblMaintanenceCert.setText("Maintanence Cert");

        lblAvailability.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblAvailability.setText("Availability");

        chkAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAvailabilityActionPerformed(evt);
            }
        });

        txtManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturerActionPerformed(evt);
            }
        });

        txtSerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNoActionPerformed(evt);
            }
        });

        txtModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNoActionPerformed(evt);
            }
        });

        lblManufacturer.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblManufacturer.setText("Manufacturer");

        txtManufactureYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufactureYearActionPerformed(evt);
            }
        });

        lblManufactureYear.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblManufactureYear.setText("Manufacture Year");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        txtsearchmanufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchmanufacturerActionPerformed(evt);
            }
        });
        txtsearchmanufacturer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchmanufacturerKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel1.setText("Filters");

        lblsortbymanufacture.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblsortbymanufacture.setText("Manufacturer");

        lblsortbyyear.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblsortbyyear.setText("ManufactureYear");

        txtsearchyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchyearActionPerformed(evt);
            }
        });
        txtsearchyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchyearKeyPressed(evt);
            }
        });

        lblsortbycity.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblsortbycity.setText("City");

        txtsearchcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchcityActionPerformed(evt);
            }
        });
        txtsearchcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchcityKeyPressed(evt);
            }
        });

        txtsearchmodelno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchmodelnoActionPerformed(evt);
            }
        });
        txtsearchmodelno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchmodelnoKeyPressed(evt);
            }
        });

        lblsortbymodelno.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblsortbymodelno.setText("Model No");

        lblsearchavailable.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblsearchavailable.setText("Availability");

        txtAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailActionPerformed(evt);
            }
        });
        txtAvail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAvailKeyPressed(evt);
            }
        });

        btnfirstavail.setText("First Available Car");
        btnfirstavail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstavailActionPerformed(evt);
            }
        });

        lblcompany.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblcompany.setText("company");

        txtcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompanyActionPerformed(evt);
            }
        });

        lblsortbycompany.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblsortbycompany.setText("Company");

        txtsearchcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchcompanyActionPerformed(evt);
            }
        });
        txtsearchcompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchcompanyKeyPressed(evt);
            }
        });

        jButton1.setText("No of seats");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnexpmain.setText("Exp Maintanence");
        btnexpmain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexpmainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete)
                            .addComponent(lblManufactureYear))
                        .addGap(48, 48, 48)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnUpdate)
                        .addGap(340, 340, 340)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblseatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblManufacturer)))
                            .addComponent(lblSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaintanenceCert)
                            .addComponent(lblAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAvailability)
                            .addComponent(txtcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtseatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSerialNo, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(txtModelNo, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(txtMaintanenceCert, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblsortbymanufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(txtsearchmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblsortbyyear)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtsearchyear, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblsortbycity, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtsearchcity, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblsortbymodelno, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblsearchavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblsortbycompany, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jButton1)
                                            .addComponent(btnfirstavail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnexpmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtseat1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtseat2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtAvail, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtsearchmodelno, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtsearchcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete)
                        .addComponent(btnView)
                        .addComponent(btnUpdate))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblseatNo)
                            .addComponent(txtseatNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblsortbymanufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsearchmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsortbyyear, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsearchyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsortbycity, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsearchcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsearchmodelno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblsortbymodelno)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblsearchavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblsortbycompany, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsearchcompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaintanenceCert, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaintanenceCert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkAvailability))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(txtseat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtseat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnfirstavail)
                        .addGap(18, 18, 18)
                        .addComponent(btnexpmain)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex= tblUber.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select row to view");
            return;
        }
        DefaultTableModel model= (DefaultTableModel) tblUber.getModel();
       Uber selectedUbers= (Uber)model.getValueAt(selectedRowIndex, 0);
       
       txtseatNo.setText(String.valueOf(selectedUbers.getSeatNo()));
       txtSerialNo.setText(selectedUbers.getSerialNo());
       txtManufactureYear.setText(String.valueOf(selectedUbers.getManufactureYear()));
      txtManufacturer.setText(selectedUbers.getManufacturer());
      txtCity.setText(selectedUbers.getCity());
      txtModelNo.setText(selectedUbers.getModelNo());
      txtMaintanenceCert.setText(String.valueOf(selectedUbers.getMaintananceCert()));
      txtcompany.setText(selectedUbers.getcompany());
     
        /*  setText(selectedUbers.)
      chkAvailability.chkavailability(selectedUbers.isAvailability());*/
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex= tblUber.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select row to delete");
            return;
        }
        DefaultTableModel model= (DefaultTableModel) tblUber.getModel();
       Uber selectedUbers= (Uber)model.getValueAt(selectedRowIndex, 0);
       history.deleteUbers(selectedUbers);
       JOptionPane.showMessageDialog(this, "Selected row deleted");
       populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        /*Date updationTime= new Date();
        Uber.setUpdationTime(updationTime);*/
        
        
        
int i=tblUber.getSelectedRow();
DefaultTableModel model= (DefaultTableModel) tblUber.getModel();
if(i>=0)
{
    model.setValueAt(txtManufacturer.getText(), i, 0);
    model.setValueAt(txtseatNo.getText(), i,1);
    model.setValueAt(txtManufactureYear.getText(), i, 2);
    model.setValueAt(txtSerialNo.getText(), i, 3);
    model.setValueAt(txtModelNo.getText(), i, 4);
    model.setValueAt(txtCity.getText(), i, 5);
    model.setValueAt(txtMaintanenceCert.getText(), i, 6);
    model.setValueAt(chkAvailability.isSelected(), i, 7);
    model.setValueAt(txtcompany.getText(), i, 8);
    
    
    
}

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtMaintanenceCertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaintanenceCertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaintanenceCertActionPerformed

    private void txtseatNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseatNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtseatNoActionPerformed

    private void chkAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAvailabilityActionPerformed

    private void txtManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturerActionPerformed

    private void txtSerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNoActionPerformed

    private void txtModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNoActionPerformed

    private void txtManufactureYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufactureYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufactureYearActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void tblUberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUberMouseClicked
        // TODO add your handling code here:

        
    }//GEN-LAST:event_tblUberMouseClicked

    private void txtsearchmanufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchmanufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchmanufacturerActionPerformed

    private void txtsearchmanufacturerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchmanufacturerKeyPressed
        // TODO add your handling code here:
 DefaultTableModel model=(DefaultTableModel) tblUber.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        tblUber.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtsearchmanufacturer.getText().trim()));
    }//GEN-LAST:event_txtsearchmanufacturerKeyPressed

    private void txtsearchyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchyearActionPerformed

    private void txtsearchyearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchyearKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) tblUber.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        tblUber.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtsearchyear.getText().trim()));
    }//GEN-LAST:event_txtsearchyearKeyPressed

    private void txtsearchcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchcityActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtsearchcityActionPerformed

    private void txtsearchcityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchcityKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) tblUber.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        tblUber.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtsearchcity.getText().trim()));
    }//GEN-LAST:event_txtsearchcityKeyPressed

    private void txtsearchmodelnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchmodelnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchmodelnoActionPerformed

    private void txtsearchmodelnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchmodelnoKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) tblUber.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        tblUber.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtsearchmodelno.getText().trim()));
    }//GEN-LAST:event_txtsearchmodelnoKeyPressed

    private void txtAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailActionPerformed

    private void txtAvailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAvailKeyPressed
        // TODO add your handling code here:
          DefaultTableModel model=(DefaultTableModel) tblUber.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        tblUber.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtAvail.getText().trim()));
    }//GEN-LAST:event_txtAvailKeyPressed

    private void btnfirstavailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstavailActionPerformed
        // TODO add your handling code here:
         String isAvailability = "true";
        populateTableFirstAvailable();
    }//GEN-LAST:event_btnfirstavailActionPerformed

    private void txtcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcompanyActionPerformed

    private void txtsearchcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchcompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchcompanyActionPerformed

    private void txtsearchcompanyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchcompanyKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) tblUber.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        tblUber.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtsearchcompany.getText().trim()));
    }//GEN-LAST:event_txtsearchcompanyKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SeatSelection();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnexpmainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexpmainActionPerformed
        // TODO add your handling code here:
        Maintanenceexp();
    }//GEN-LAST:event_btnexpmainActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnexpmain;
    private javax.swing.JButton btnfirstavail;
    private javax.swing.JCheckBox chkAvailability;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblMaintanenceCert;
    private javax.swing.JLabel lblManufactureYear;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblModelNo;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblcompany;
    private javax.swing.JLabel lblsearchavailable;
    private javax.swing.JLabel lblseatNo;
    private javax.swing.JLabel lblsortbycity;
    private javax.swing.JLabel lblsortbycompany;
    private javax.swing.JLabel lblsortbymanufacture;
    private javax.swing.JLabel lblsortbymodelno;
    private javax.swing.JLabel lblsortbyyear;
    private javax.swing.JTable tblUber;
    private javax.swing.JTextField txtAvail;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtMaintanenceCert;
    private javax.swing.JTextField txtManufactureYear;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtSerialNo;
    private javax.swing.JTextField txtcompany;
    private javax.swing.JTextField txtsearchcity;
    private javax.swing.JTextField txtsearchcompany;
    private javax.swing.JTextField txtsearchmanufacturer;
    private javax.swing.JTextField txtsearchmodelno;
    private javax.swing.JTextField txtsearchyear;
    private javax.swing.JTextField txtseat1;
    private javax.swing.JTextField txtseat2;
    private javax.swing.JTextField txtseatNo;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model= (DefaultTableModel) tblUber.getModel();
        model.setRowCount(0);
         for (Uber u:history.getHistory()){
             
             Object[] row= new Object[9];
             row[0]= u;
             row[1]= u.getSeatNo();
             row[2]= u.getManufactureYear();
             row[3]= u.getSerialNo();
             row[4]= u.getModelNo();
             row[5]= u.getCity();
             row[6]= u.getMaintananceCert();
             row[7]= u.isAvailability();
             row[8]=u.getcompany();
           
             model.addRow(row);
             
         }
        
    }
            private void populateTableFirstAvailable() {
            DefaultTableModel model = (DefaultTableModel) tblUber.getModel();
            model.setRowCount(0);

            for(Uber u: history.getHistory()) {

                if(u.isAvailability()== true) {
             Object[] row= new Object[9];
             row[0]= u;
             row[1]= u.getSeatNo();
             row[2]= u.getManufactureYear();
             row[3]= u.getSerialNo();
             row[4]= u.getModelNo();
             row[5]= u.getCity();
             row[6]= u.getMaintananceCert();
             row[7]= u.isAvailability();
             row[8]=u.getcompany();
                    if (model.getRowCount() == 0) {
                        model.addRow(row);
                    }
                }
            }

        }
            private void SeatSelection() {
        DefaultTableModel model = (DefaultTableModel) tblUber.getModel();
        model.setRowCount(0);

        if (txtseat1.getText().isBlank() && txtseat2.getText().isBlank())
            {
                        JOptionPane.showMessageDialog(this, " seat numebr cant be blank");

            }
        else{
        int seat1 = Integer.parseInt(txtseat1.getText());
        int seat2 = Integer.parseInt(txtseat2.getText());


        for(Uber u: history.getHistory()) {
        int seatCap = u.getSeatNo();

        if(seatCap>= seat1 && seatCap<=seat2) {
             Object[] row= new Object[9];
             row[0]= u;
             row[1]= u.getSeatNo();
             row[2]= u.getManufactureYear();
             row[3]= u.getSerialNo();
             row[4]= u.getModelNo();
             row[5]= u.getCity();
             row[6]= u.getMaintananceCert();
             row[7]= u.isAvailability();
             row[8]=u.getcompany();
            model.addRow(row);
        }
        }
        }
        }
        private void Maintanenceexp() {
        DefaultTableModel model = (DefaultTableModel) tblUber.getModel();
        model.setRowCount(0);
for(Uber u: history.getHistory()){
int maint=u.getMaintananceCert();
        if(maint<=50) {
             Object[] row= new Object[9];
             row[0]= u;
             row[1]= u.getSeatNo();
             row[2]= u.getManufactureYear();
             row[3]= u.getSerialNo();
             row[4]= u.getModelNo();
             row[5]= u.getCity();
             row[6]= u.getMaintananceCert();
             row[7]= u.isAvailability();
             row[8]=u.getcompany();
            model.addRow(row);
        }
        }
        }
        }

